<script setup lang="ts">
const runtime=uni;
import { ref } from 'vue';import { onLoad,onShow,onHide,onUnload } from '@dcloudio/uni-app';
import CommitteeThumbnail from '@/components/CommitteeThumbnail.vue';
import AppNavBar from '@/components/AppNavBar.vue';import CommitteePreview from '@/components/CommitteePreview.vue';
import { useAuthStore } from '@/stores/auth';import { request } from '@/api/request';
import { committeeApi,committeeDate,committeeSize,committeeAccessLost,activeCommitteeFiles,type CommitteeRecord,type CommitteeAttachment } from '@/api/safetyCommittee';
const auth=useAuthStore();const id=ref(0);const record=ref<CommitteeRecord>();const preview=ref<CommitteeAttachment>();const error=ref('');const expanded=ref<number>();let timer:ReturnType<typeof setInterval>|undefined;let visible=false;let loading=false;
async function refresh(){if(!id.value||!visible||loading)return;loading=true;try{const next=await committeeApi.detail(id.value);if(visible)record.value=next;}catch(e){error.value=(e as Error).message;if(committeeAccessLost(e)){record.value=undefined;preview.value=undefined;}}finally{loading=false;}}
onLoad(o=>{id.value=Number(o?.id)||0;void refresh();});onShow(async()=>{visible=true;if(!await auth.ensureRootAccess('/pages/safety-committee/index'))return;await refresh();clearInterval(timer);timer=setInterval(refresh,5000);});
function stop(){visible=false;clearInterval(timer);}onHide(stop);onUnload(stop);
function snapshot(raw:string){try{return JSON.parse(raw) as {category:string;conclusion:string;attachmentIds:number[]};}catch{return null;}}
function historyFiles(raw:string){return record.value?.attachments.filter(a=>snapshot(raw)?.attachmentIds?.includes(a.id))||[];}
async function remove(){try{const impact=await request<any>('/system/deletions/preview',{method:'POST',data:{targetType:'COMMITTEE_INSPECTION',targetId:id.value}});
 const content=`${impact.targetName}\n${impact.items.map((i:any)=>`${i.label}：${i.count}`).join('\n')}\n文件：${impact.fileCount} 个\n永久删除无法恢复，请确认已核对以上影响。`;
 const result=await new Promise<UniApp.ShowModalRes>(resolve=>uni.showModal({title:'删除影响确认',content,confirmText:'已核对删除',confirmColor:'#c34444',success:resolve}));
 if(!result.confirm)return;await request('/system/deletions/execute',{method:'POST',data:{targetType:impact.targetType,targetId:id.value,confirmationToken:impact.confirmationToken,acknowledged:true}});uni.navigateBack();
 }catch(e){error.value=(e as Error).message;}}
</script>
<template><view class="committee-page"><AppNavBar title="安委会巡检" @back="runtime.navigateBack({fail:()=>runtime.reLaunch({url:'/pages/safety-committee/index'})})"/><view class="committee-content"><view v-if="error" class="committee-error">{{error}}</view><template v-if="record"><view class="committee-card"><text class="committee-tag">{{record.category}}</text><text class="committee-title">{{record.inspectorName}}的巡检记录</text><text class="committee-muted">{{committeeDate(record.inspectedAt)}} · 北京时间</text><text class="committee-muted">第 {{record.version}} 版</text><text class="committee-conclusion">{{record.conclusion||'未填写检查结论'}}</text><view v-for="a in activeCommitteeFiles(record)" :key="a.id" class="committee-file" @tap="preview=a"><CommitteeThumbnail :attachment="a" @open="preview=a"/><view><text>{{a.fileName}}</text><text class="committee-muted">{{committeeSize(a.fileSize)}} · {{a.previewStatus==='READY'?'点击预览':a.previewStatus==='FAILED'?'预览失败，可下载原件':'预览处理中'}}</text></view></view><text v-if="!activeCommitteeFiles(record).length" class="committee-muted">无现场附件</text><view class="committee-actions"><button v-if="record.canEdit" @tap="runtime.navigateTo({url:`/pages/safety-committee/edit?id=${record.id}`})">修改本人记录</button><button v-if="record.canDelete" @tap="remove">永久删除</button></view></view>
 <view class="committee-card"><text class="committee-title">修改记录</text><view v-for="log in record.logs" :key="log.id" class="committee-log"><text>{{log.operatorName}} · {{log.action==='CREATE'?'上报巡检':log.action==='EDIT'?'修改巡检':'重试预览'}}</text><text class="committee-muted">{{committeeDate(log.createTime)}}</text><button v-if="log.action==='EDIT'" @tap="expanded=expanded===log.id?undefined:log.id">{{expanded===log.id?'收起':'查看修改内容'}}</button><template v-if="expanded===log.id"><view v-for="part in [{label:'修改前',raw:log.beforeJson},{label:'修改后',raw:log.afterJson}]" :key="part.label"><text class="committee-tag">{{part.label}}</text><text class="committee-muted">{{snapshot(part.raw)?.category}}</text><text class="committee-conclusion">{{snapshot(part.raw)?.conclusion||'未填写结论'}}</text><view v-for="a in historyFiles(part.raw)" :key="a.id" class="committee-file" @tap="preview=a">{{a.fileName}} · {{a.status==='HISTORICAL'?'历史附件':'当前附件'}} ›</view></view></template></view></view>
 </template></view><CommitteePreview v-if="preview" :key="preview.id" :attachment="preview" :can-retry="record?.canEdit||record?.canDelete" @close="preview=undefined"/></view></template>
<style>@import "./committee.css";</style>
