[Unit]
Wants=network-online.target
After=network-online.target mysql.service redis-server.service
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Restart=on-failure
RestartSec=20s
TimeoutStartSec=120s
TimeoutStopSec=60s
