package com.example.siteplatform.system.dto;

import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RoleAuthorizationRequestValidationTest {

    private static ValidatorFactory validatorFactory;
    private static Validator validator;

    @BeforeAll
    static void setUpValidator() {
        validatorFactory = Validation.buildDefaultValidatorFactory();
        validator = validatorFactory.getValidator();
    }

    @AfterAll
    static void closeValidator() {
        validatorFactory.close();
    }

    @Test
    void menuRequestRequiresExplicitArraysAndKnownBusinessModules() {
        RoleMenuUpdateRequest request = new RoleMenuUpdateRequest();
        assertFalse(validator.validate(request).isEmpty());

        request.setMenuIds(List.of(1L));
        request.setBusinessModuleCodes(List.of("UNKNOWN"));
        assertFalse(validator.validate(request).isEmpty());

        request.setBusinessModuleCodes(List.of("SITE_ACCESS", "DOCUMENT", "INSPECTION", "QUALITY"));
        assertTrue(validator.validate(request).isEmpty());
    }

    @Test
    void operationPermissionRequestAllowsExplicitClearButRejectsInvalidIds() {
        RoleOperationPermissionUpdateRequest request = new RoleOperationPermissionUpdateRequest();
        request.setPermissionIds(List.of());
        assertTrue(validator.validate(request).isEmpty());

        request.setPermissionIds(List.of(-1L));
        assertFalse(validator.validate(request).isEmpty());
    }

    @Test
    void roleSaveRequestAllowsMissingAutoGeneratedCodeButValidatesLegacyCode() {
        RoleSaveRequest request = new RoleSaveRequest();
        request.setRoleName("材料查看员");
        request.setRoleCode(null);
        assertTrue(validator.validate(request).isEmpty());

        request.setRoleCode("invalid code");
        assertFalse(validator.validate(request).isEmpty());

        request.setRoleCode("CUSTOM_REVIEWER");
        assertTrue(validator.validate(request).isEmpty());
    }
}
