import { useCallback, useEffect, useRef, useState } from 'react';
import { corrections, uploadCorrection } from '../../services/dataCorrections';
import CorrectionModuleCatalog, { CorrectionPageHeader } from './CorrectionModuleCatalog';
import './dataCorrections.css';
const show = (value) => value == null || value === '' ? '—' : /Z$/.test(String(value)) ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : String(value).replace('T', ' ');
const equal = (a, b) => String(a ?? '') === String(b ?? '');
const labels = { created_by: '创建人编号', uploader_id: '原上传人编号', task_id: '所属检查任务', point_id: '所属点位', plan_id: '原计划', electric_box_id: '所属电箱', inspection_record_id: '所属日检', weekly_inspection_id: '所属周检', invitation_id: '所属邀请', registration_source: '登记来源', valid_until: '原有效截止时间', received_at: '实际收文时间', receiver_name: '实际收文人', published_time: '实际发布时间', published_by_name: '实际发布人', document_type: '资料类型', deadline: '原期限', seal_name: '印章', submit_time: '实际提交时间', approval_opinion: '实际审批意见', qr_status: '二维码状态', occurrence_date: '计划生成日期', rectified_time: '实际整改时间', sort_order: '原顺序', item_order: '原顺序', status: '流程状态', create_time: '系统创建时间', submitted_time: '实际提交时间', submitted_by_name: '实际提交人', created_by_name: '创建人', approval_time: '实际审批时间', approver_name: '实际审批人', reviewer_name: '实际复查人', review_time: '实际复查时间', registered_time: '实际登记时间', visit_start_time: '邀请开始时间', visit_end_time: '邀请结束时间', completed_time: '实际整改时间', close_time: '实际闭环时间', result: '检查结果', item_name: '检查项目', week_start: '所属周一', abnormal_count: '异常数量', project_status: '项目状态', person_type: '人员类型', published_version_id: '已公开版本', stamped_result_required: '要求盖章件', application_id: '关联申请', parent_id: '上级目录', folder_id: '所属目录', review_status: '复查状态', review_comment: '实际复查意见', category_name: '类别' };
const options = { REGISTERED: '已登记', PENDING_APPROVAL: '待审批', REJECTED: '已退回', RECTIFICATION_PENDING: '待整改', WITHDRAWN: '已撤回', DRIVING: '驾车', OTHER: '其他', NORMAL: '一般', WARNING: '较重', DANGER: '严重', PUBLICITY: '宣传资料', AGENDA: '议程', MINUTES: '纪要', MEDIA: '影像', OTHER_DOCUMENT: '其他', PROJECT_DATA: '工程资料', DRAWING: '图纸', FORM: '表格', CONSTRUCTION_RECORD: '施工记录', MEETING: '会议', APPROVED: '已批准', CLOSED: '已闭环', SUBMITTED: '已提交', DRAFT: '草稿', ACTIVE: '有效', ARCHIVED: '已归档', PENDING: '待处理', COMPLETED: '已完成', VOIDED: '已作废', CANCELLED: '已取消', ABNORMAL: '异常' };
const display = (value) => options[value] || show(value);
function delta(before, after, type) {
  const rows = [];
  for (const f of type.fields) if (!equal(before.values[f.key], after.values[f.key])) rows.push([f.label, f.type === 'USER' ? `${before.names?.[f.key] || ''} (#${before.values[f.key]})` : before.values[f.key], f.type === 'USER' ? `${after.names?.[f.key] || ''} (#${after.values[f.key]})` : after.values[f.key]]);
  for (const c of type.children) for (const r of after.children[c.key] || []) {
    const old = (before.children[c.key] || []).find((x) => x.id === r.id);
    for (const f of c.fields) if (!equal(old?.values[f.key], r.values[f.key])) rows.push([`${c.label} #${r.id} · ${f.label}`, old?.values[f.key], r.values[f.key]]);
  }
  for (const s of type.slots) {
    const old = before.attachments[s.key] || []; const next = after.attachments[s.key] || [];
    if (JSON.stringify(old) !== JSON.stringify(next)) rows.push([s.label, old.map((f) => `${f.name} (#${f.id})`).join('、'), next.map((f) => `${f.name} (#${f.id})`).join('、')]);
  }
  for (const r of after.relatedRecords || []) {
    const old = (before.relatedRecords || []).find((v) => v.id === r.id && v.label === r.label);
    for (const [key, value] of Object.entries(r.values)) if (!equal(old?.values[key], value)) rows.push([`${r.label} #${r.id} · ${{ record_date: '业务日期', assignee_id: '整改人编号', assignee_name: '整改人' }[key] || key}`, old?.values[key], value]);
  }
  return rows;
}
function Comparison({ before, after, type }) {
  return <table className="correction-diff"><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody>{delta(before, after, type).map(([key, old, next]) => <tr key={key}><th>{key}</th><td>{display(old)}</td><td>{display(next)}</td></tr>)}</tbody></table>;
}
export function CorrectionLogDialog({ id, ModalFrame, onClose }) {
  const [log, setLog] = useState(null); const [type, setType] = useState(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; Promise.all([corrections.log(id), corrections.catalog()]).then(([value, catalog]) => { if (active) { setLog(value); setType({ ...catalog.find((t) => t.code === value.target_type), slots: value.after.slots || [] }); } }).catch((e) => { if (active) setError(e.message); }); return () => { active = false; }; }, [id]);
  return <ModalFrame title="纠错操作详情" onClose={onClose} footer={<button onClick={onClose}>关闭</button>}><div className="correction-editor">{error && <p role="alert">{error}</p>}{!log && !error && <p>加载中…</p>}{log && type && <><p>{log.target_label} #{log.target_id} · {log.operator_name} · {show(log.create_time)}</p><p>纠错原因：{log.reason}</p><Comparison before={log.before} after={log.after} type={type} />{['before', 'after'].map((phase) => <section key={phase}><h4>{phase === 'before' ? '修改前附件' : '修改后附件'}</h4>{type.slots.map((slot) => <FileLinks key={slot.key} record={log[phase]} files={log[phase].attachments[slot.key] || []} correctionId={id} phase={phase.toUpperCase()} />)}</section>)}</>}</div></ModalFrame>;
}
function FileLinks({ record, files, correctionId, phase, remove, disabled }) {
  const [error, setError] = useState(''); const [media, setMedia] = useState(null);
  useEffect(() => () => { if (media) URL.revokeObjectURL(media.url); }, [media]);
  const open = async (file) => {
    try {
      setError(''); const blob = await corrections.file(record.targetType, record.id, file.id, correctionId, phase); const url = URL.createObjectURL(blob);
      if (['jpg','jpeg','png','gif','webp','bmp','pdf','mp4','mov'].includes(file.extension)) setMedia({ url, ...file });
      else { const a = document.createElement('a'); a.href = url; a.download = file.name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    } catch (e) { setError(e.message || '附件读取失败'); }
  };
  return <><ul className="correction-files">{files.map((file) => <li key={file.id}><button type="button" onClick={() => void open(file)}>{file.name}</button><small>{(file.size / 1024 / 1024).toFixed(2)} MB</small>{remove && <button type="button" disabled={disabled} onClick={() => remove(file.id)}>移除</button>}</li>)}</ul>{error && <p role="alert">{error}</p>}{media && <div className="correction-media" role="dialog" aria-label={media.name}><button type="button" onClick={() => setMedia(null)}>关闭附件预览</button>{media.extension === 'pdf' ? <iframe title={media.name} src={media.url} /> : ['mp4','mov'].includes(media.extension) ? <video controls src={media.url} /> : <img alt={media.name} src={media.url} />}</div>}</>;
}
function PersonField({ record, field, value, onChange, disabled }) {
  const [people, setPeople] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  useEffect(() => { let active = true; corrections.candidates(record.targetType, record.id, field.key).then((r) => { if (active) setPeople(r); }).catch((e) => { if (active) setError(e.message); }); return () => { active = false; }; }, [record.targetType, record.id, field.key]);
  return <><input aria-label={`搜索${field.label}`} placeholder="搜索姓名或账号" value={search} disabled={disabled} onChange={(e) => setSearch(e.target.value)} /><select value={value ?? ''} disabled={disabled} onChange={(e) => onChange(e.target.value)}><option value={value ?? ''}>{people.find((p) => String(p.id) === String(value))?.real_name || record.names?.[field.key] || `当前人员 #${value || '未设置'}`}</option>{people.filter((p) => `${p.real_name} ${p.username}`.includes(search) && String(p.id) !== String(value)).map((p) => <option key={p.id} value={p.id}>{p.real_name || p.username}（{p.username}）</option>)}</select>{error && <span role="alert">{error}</span>}</>;
}
function Field({ field, value, onChange, record, disabled }) {
  return <label className="correction-field"><span>{field.label}{field.required ? ' *' : ''}</span>{field.type === 'USER' ? <PersonField {...{ field, value, onChange, record, disabled }} /> : field.type === 'ENUM' ? <select disabled={disabled} value={value ?? ''} onChange={(e) => onChange(e.target.value)}><option value="">请选择</option>{field.options.map((v) => <option key={v} value={v}>{display(v)}</option>)}</select> : field.type === 'TEXTAREA' ? <textarea disabled={disabled} value={value ?? ''} maxLength={field.maxLength} onChange={(e) => onChange(e.target.value)} /> : <input disabled={disabled} type={field.type === 'DATE' ? 'date' : field.type === 'DATETIME' ? 'datetime-local' : ['INTEGER','DECIMAL'].includes(field.type) ? 'number' : 'text'} step={field.type === 'DECIMAL' ? 'any' : field.type === 'DATETIME' ? '1' : undefined} maxLength={field.maxLength || undefined} value={value ?? ''} onChange={(e) => onChange(e.target.value)} />}</label>;
}
function Editor({ type, record, currentUser, ModalFrame, onClose, onSaved }) {
  const [base, setBase] = useState(record); const [draft, setDraft] = useState(structuredClone(record)); const [reason, setReason] = useState(''); const [confirmedLocation, setConfirmedLocation] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [conflict, setConflict] = useState(false); const [review, setReview] = useState(null); const [history, setHistory] = useState(null); const [historyPage, setHistoryPage] = useState(1); const [log, setLog] = useState(null); const [progress, setProgress] = useState(''); const upload = useRef(null);
  useEffect(() => () => upload.current?.abort(), []);
  const preview = async () => {
    setBusy(true); setError('');
    const changes = Object.fromEntries(Object.entries(draft.values).filter(([k,v]) => !equal(v,base.values[k])));
    const children = Object.fromEntries(type.children.map((c) => [c.key, draft.children[c.key].map((r) => ({ id: r.id, ...Object.fromEntries(Object.entries(r.values).filter(([k,v]) => !equal(v,base.children[c.key].find((x) => x.id === r.id)?.values[k]))) }))]));
    const attachments = Object.fromEntries(type.slots.filter((s) => JSON.stringify(draft.attachments[s.key].map((f) => f.id)) !== JSON.stringify(base.attachments[s.key].map((f) => f.id))).map((s) => [s.key, draft.attachments[s.key].map((f) => f.id)]));
    try { const result = await corrections.preview(type.code, record.id, { expectedRevision: base.expectedRevision, reason, changes, children, attachments, confirmLocation: confirmedLocation }); setReview({ ...result, requestKey: crypto.randomUUID() }); }
    catch (e) { setError(e.message); setConflict(e.response?.status === 409); } finally { setBusy(false); }
  };
  const save = async () => { setBusy(true); setError(''); try { await corrections.confirm({ confirmationToken: review.confirmationToken, requestKey: review.requestKey }); onSaved(); } catch (e) { setError(e.message); if (e.response?.status === 409) { setConflict(true); setReview(null); } } finally { setBusy(false); } };
  const recheck = async () => { setBusy(true); try { const latest = await corrections.detail(type.code, record.id); setBase(latest); setError('已加载最新内容作为修改前值，您的输入已保留。请重新查看修改前后对照。'); setConflict(false); setReview(null); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const addFiles = async (slot, files) => {
    if (draft.attachments[slot.key].length + files.length > slot.max) { setError(`${slot.label}最多 ${slot.max} 个，请先移除要替换的附件`); return; }
    setBusy(true); setError(''); upload.current = new AbortController();
    try { for (const file of files) { const added = await uploadCorrection(file, record, slot.key, currentUser.id, setProgress, upload.current.signal); setDraft((d) => ({ ...d, attachments: { ...d.attachments, [slot.key]: [...d.attachments[slot.key], added] } })); } } catch (e) { setError(e.message); } finally { setBusy(false); setProgress(''); }
  };
  const loadHistory = async (page = 1) => { try { setHistory(await corrections.history(type.code, record.id, page)); setHistoryPage(page); } catch (e) { setError(e.message); } };
  return <ModalFrame title={`${type.label} #${record.id} · 数据纠错`} onClose={() => { if (!busy) onClose(); }} footer={<><button disabled={busy} onClick={onClose}>取消</button>{review ? <><button disabled={busy} onClick={() => setReview(null)}>返回修改</button><button className="primary" disabled={busy} onClick={save}>{busy ? '保存中…' : '确认保存并留痕'}</button></> : <button className="primary" disabled={busy || conflict || !reason.trim()} onClick={preview}>{busy ? '处理中…' : '查看修改前后对照'}</button>}</>}>
    <div className="correction-editor">{error && <div className="system-form-error" role="alert">{error}{conflict && <button disabled={busy} onClick={recheck}>保留输入，重新核对</button>}</div>}{review ? <><p>纠错原因：{reason}</p><p>确认有效期至 {show(review.expiresAt)}。保存会保留原流程状态及实际操作事件。</p><Comparison before={review.before} after={review.after} type={type} /></> : <><div className="correction-readonly">{Object.entries(base.readOnly).map(([k,v]) => <span key={k}>{labels[k] || k}：{display(v)}</span>)}</div><div className="correction-fields">{type.fields.map((field) => <Field key={field.key} field={field} value={draft.values[field.key]} record={base} disabled={busy} onChange={(v) => setDraft((d) => ({ ...d, values: { ...d.values, [field.key]: v } }))} />)}</div>
    {type.children.map((c) => <section key={c.key}><h4>{c.label}</h4>{draft.children[c.key].map((row) => <div className="correction-child" key={row.id}><p>#{row.id} · {Object.values(row.readOnly).map(display).join(' / ')}</p><div className="correction-fields">{c.fields.map((field) => <Field key={field.key} field={field} value={row.values[field.key]} record={base} disabled={busy} onChange={(v) => setDraft((d) => ({ ...d, children: { ...d.children, [c.key]: d.children[c.key].map((r) => r.id === row.id ? { ...r, values: { ...r.values, [field.key]: v } } : r) } }))} />)}</div></div>)}</section>)}
    {type.slots.map((slot) => <section className="correction-slot" key={slot.key}><h4>{slot.label} <small>最多 {slot.max} 个；替换时先移除旧附件再添加</small></h4><FileLinks record={base} files={draft.attachments[slot.key]} disabled={busy} remove={(id) => setDraft((d) => ({ ...d, attachments: { ...d.attachments, [slot.key]: d.attachments[slot.key].filter((f) => f.id !== id) } }))} /><input aria-label={`添加${slot.label}`} type="file" multiple={slot.max > 1} disabled={busy} onChange={(e) => { void addFiles(slot, [...e.target.files]); e.target.value = ''; }} /></section>)}{progress && <p role="status">{progress}</p>}
    {type.code === 'PROJECT_LOCATION' && <label><input type="checkbox" checked={confirmedLocation} onChange={(e) => setConfirmedLocation(e.target.checked)} />我已核对地址、坐标来源和定位点</label>}
    <label className="correction-field"><span>纠错原因 *</span><textarea maxLength={500} value={reason} disabled={busy} placeholder="填写本次修改的原因，最多500字" onChange={(e) => setReason(e.target.value)} /></label><button type="button" onClick={() => void loadHistory()}>查看纠错历史</button>{history && <section><h4>纠错历史（{history.total} 条）</h4>{history.records.map((r) => <p key={r.id}><button onClick={() => setLog(r.id)}>{show(r.create_time)} · {r.operator_name} · {r.reason}</button></p>)}<button disabled={historyPage <= 1} onClick={() => void loadHistory(historyPage - 1)}>上一页</button><button disabled={historyPage * 20 >= history.total} onClick={() => void loadHistory(historyPage + 1)}>下一页</button></section>}</>}{log && <CorrectionLogDialog id={log} ModalFrame={ModalFrame} onClose={() => setLog(null)} />}</div>
  </ModalFrame>;
}
export default function DataCorrections({ currentUser, projectList, initialProjectId, ModalFrame, Pagination }) {
  const [catalog, setCatalog] = useState([]); const [type, setType] = useState(null); const [projectId, setProjectId] = useState(initialProjectId || projectList[0]?.id || '');
  const [filter, setFilter] = useState({ keyword: '', startDate: '', endDate: '', status: '' }); const [query, setQuery] = useState({}); const [pageNo, setPageNo] = useState(1); const [pageSize, setPageSize] = useState(20);
  const [data, setData] = useState({ records: [], total: 0 }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(''); const sequence = useRef(0); const scroller = useRef(null);
  useEffect(() => { if (!projectId && projectList[0]?.id) setProjectId(projectList[0].id); }, [projectId, projectList]);
  useEffect(() => { let active = true; corrections.catalog().then((r) => { if (active) setCatalog(r); }).catch((e) => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  const load = useCallback(async () => {
    const seq = ++sequence.current; if (!type || !projectId) return; setLoading(true); setError('');
    try { const rows = await corrections.list(type.code, { projectId, ...query, pageNo, pageSize }); if (seq === sequence.current) setData(rows); }
    catch (e) { if (seq === sequence.current) { setError(e.message); setData({ records: [], total: 0 }); } }
    finally { if (seq === sequence.current) setLoading(false); }
  }, [type, projectId, query, pageNo, pageSize]);
  useEffect(() => { void load(); scroller.current?.scrollTo(0,0); return () => { sequence.current += 1; }; }, [load]);
  const open = async (row) => { setError(''); try { setEditing(await corrections.detail(type.code, row.id)); } catch (e) { setError(e.message); } };
  return <div className={`data-corrections${!type ? ' is-catalog' : ''}`}><CorrectionPageHeader />{message && <div className="system-inline-notice" role="status">{message}</div>}{error && <div className="system-form-error" role="alert">{error}<button onClick={load}>重试</button></div>}
  {!type ? <CorrectionModuleCatalog catalog={catalog} onSelect={(selected) => { setType(selected); setPageNo(1); setQuery({}); setFilter({keyword:'',startDate:'',endDate:'',status:''}); }} /> : <><div className="correction-heading"><button onClick={() => setType(null)}>← 模块目录</button><h3>{type.group} / {type.label}</h3></div><form className="correction-filters" onSubmit={(e) => { e.preventDefault(); setQuery(Object.fromEntries(Object.entries(filter).filter(([,v]) => v))); setPageNo(1); }}><select aria-label="纠错项目" value={projectId} onChange={(e) => { setProjectId(e.target.value); setPageNo(1); }}>{projectList.map((p) => <option key={p.id} value={p.id}>{p.projectName || p.shortName}</option>)}</select><input aria-label="关键词" placeholder="名称或编号关键词" value={filter.keyword} onChange={(e) => setFilter({...filter,keyword:e.target.value})} /><input aria-label="开始日期" type="date" value={filter.startDate} onChange={(e) => setFilter({...filter,startDate:e.target.value})} /><span>至</span><input aria-label="结束日期" type="date" value={filter.endDate} onChange={(e) => setFilter({...filter,endDate:e.target.value})} />{type.readOnly.includes('status') && <select aria-label="状态" value={filter.status} onChange={(e) => setFilter({...filter,status:e.target.value})}><option value="">全部状态</option>{['ACTIVE','DRAFT','SUBMITTED','REGISTERED','PENDING','PENDING_APPROVAL','APPROVED','REJECTED','NORMAL','RECTIFICATION_PENDING','COMPLETED','CLOSED','ARCHIVED','WITHDRAWN','VOIDED','CANCELLED'].map((s) => <option key={s} value={s}>{display(s)}</option>)}</select>}<button className="primary">查询</button><button type="button" onClick={() => { setFilter({ keyword:'',startDate:'',endDate:'',status:'' });setQuery({});setPageNo(1); }}>重置</button></form>
  <div className="correction-list" ref={scroller}><table><thead><tr><th>记录</th><th>业务日期 / 创建日期</th><th>状态</th><th>最近纠错</th><th>操作</th></tr></thead><tbody>{data.records.map((r) => <tr key={r.id}><td>{r.title || type.label}<small>#{r.id}</small></td><td>{show(r.date)}</td><td>{display(r.status)}</td><td>{r.lastCorrection ? `${r.lastCorrection.operator_name} · ${show(r.lastCorrection.create_time)}` : '—'}</td><td><button disabled={loading} onClick={() => void open(r)}>纠错 / 历史</button></td></tr>)}{!data.records.length && <tr><td colSpan={5}>{loading ? '加载中…' : '暂无匹配记录'}</td></tr>}</tbody></table></div><Pagination pageNo={pageNo} pageSize={pageSize} total={data.total} currentCount={data.records.length} disabled={loading} onPageChange={setPageNo} onPageSizeChange={(size) => {setPageSize(size);setPageNo(1);}} /></>}{editing && <Editor currentUser={currentUser} type={{ ...type, slots: editing.slots || type.slots }} record={editing} ModalFrame={ModalFrame} onClose={() => setEditing(null)} onSaved={() => { setEditing(null);setMessage('纠错已保存，操作日志及修改前后内容已留存。');void load(); }} />}</div>;
}
